# Generated by Django 2.2.5 on 2019-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_respuestas_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo',
            field=models.TextField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
