# Generated by Django 2.2.5 on 2019-09-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20190908_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuesta.Cuestionario'),
            preserve_default=False,
        ),
    ]
