# Generated by Django 2.2.5 on 2019-09-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_auto_20190908_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta',
        ),
    ]
