# Generated by Django 2.2.5 on 2019-09-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_remove_respuestas_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='encuesta.Preguntas'),
            preserve_default=False,
        ),
    ]
