# Generated by Django 2.2.5 on 2019-09-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_auto_20190922_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'texto'), ('si_no', 'si_no'), ('multiple', 'multiple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntaR', to='encuesta.Preguntas'),
        ),
    ]
