# Generated by Django 2.2.5 on 2019-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0009_auto_20190922_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
