# Generated by Django 2.2.5 on 2019-09-30 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_auto_20190922_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizaciones',
            name='id',
        ),
        migrations.AddField(
            model_name='organizaciones',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
