# Generated by Django 2.2.5 on 2019-09-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0012_auto_20190929_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='cuestionario',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
    ]
